### ISSUE TITLE
embading isue

### ISSUE THREAD

**Issue by sidrasarwarr** [ImBharatkumar/Document-Chat-Bot#1]
how to download embading from openai????

**Comment by ImBharatkumar** [comment]
Could you specify where you facing problem with line of code, so that i can answer specifically

**Comment by sidrasarwarr** [comment]
sure i will send problem

**Comment by sidrasarwarr** [comment]
# Download embeddings from OpenAI
embeddings = OpenAIEmbeddings()

docsearch = FAISS.from_texts(texts, embeddings)

i face this error   

RateLimitError: You exceeded your current quota, please check your plan and billing details.

**Comment by sidrasarwarr** [comment]
RateLimitError                            Traceback (most recent call last)
<ipython-input-14-42880e340ce0> in <cell line: 1>()
----> 1 docsearch = FAISS.from_texts(texts, embeddings)

16 frames
/usr/local/lib/python3.10/dist-packages/openai/api_requestor.py in _interpret_response_line(self, rbody, rcode, rheaders, stream)
    773         stream_error = stream and "error" in resp.data
    774         if stream_error or not 200 <= rcode < 300:
--> 775             raise self.handle_error_response(
    776                 rbody, rcode, resp.data, rheaders, stream_error=stream_error
    777             )

RateLimitError: You exceeded your current quota, please check your plan and billing details.

**Comment by ImBharatkumar** [comment]
You have exceeded chat got free tire, u need to pay or need to create new account with new gmail with new mob number

**Comment by sidrasarwarr** [comment]
i create new gmail account.but still embading isue

**Comment by sidrasarwarr** [comment]
please share any youtube video to resolve my isue

**Comment by sidrasarwarr** [comment]
tell me please

**Comment by sidrasarwarr** [comment]
i create new gmail acount and still i face this error ..

**Comment by ImBharatkumar** [comment]
You need to create with , new mobile number and generate chat gpt api key, then paste it in place provided in code.

**Comment by sidrasarwarr** [comment]
i cant understand 
please send me your gmail acount. i will send mobile no then i will disscuss

**Comment by ImBharatkumar** [comment]
bharatkumargkori@gmail.com
